# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Prasun Anand's blog
email: prasunanand.bitsp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  GSoC 2017, GSoC 2016, SciRuby, Polyglot, Scientific Programmer, BioInformatics, BITSian, FOSS supporter, GPU, HPC
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: prasun_anand
github_username:  prasunanand

# Build settings
markdown: kramdown
